Add --force option + error for missing virtualenv.

diff --git a/bin/rose-make-docs b/bin/rose-make-docs
--- a/bin/rose-make-docs
+++ b/bin/rose-make-docs
@@ -99,8 +99,15 @@ venv-destroy () {
     rm -rf "${VENV_PATH}"
 }
 
+if $(which virtualenv >/dev/null 2>/dev/null); then
+    VENV_COMPLIANT=true
+else
+    VENV_COMPLIANT=false
+fi
+
 # Parse command line args.
 VENV_MODE=false
+FORCE=false
 DEV_MODE=${SPHINX_DEV_MODE:=false}
 BUILDS=''
 while [[ $# -gt 0 ]]; do
@@ -111,6 +118,10 @@ while [[ $# -gt 0 ]]; do
             ;;
         --dev)
             DEV_MODE=true
+            shift
+            ;;
+        --force)
+            FORCE=true
             shift
             ;;
         *)
@@ -125,6 +136,10 @@ fi
 
 # Use virtualenv if present and requested or if we are in development mode.
 if [[ "${DEV_MODE}" != 'false' || "${VENV_MODE}" != false ]]; then
+    if [[ -z "${VENV_COMPLIANT}" ]]; then
+        echo 'The virtualenv command is required for the --venv option.'
+        exit 1
+    fi
     if [ -d "${VENV_PATH}" ]; then
         venv-activate
     fi
@@ -134,17 +149,30 @@ fi
 if ! rose-check-software --doc >/dev/null; then
     if ${VENV_MODE}; then
         venv-install
-    else
+    elif [[ "${FORCE}" == 'false' ]]; then
         echo "$(rose check-software --doc)"
         echo "$(python -c 'import sphinxcontrib.httpdomain')"
         echo 'Software required by the rose documentation builder is not'
         echo 'present (run `rose check-software --doc` for details).'
+
+        if [[ "${VENV_COMPLIANT}" == 'false' ]]; then
+            echo
+            echo 'Unable to build documentation.'
+            echo
+            echo 'To override the dependency checking logic and force the '
+            echo 'docs to build use the "--force" option.'
+            exit 1
+        fi
+
         echo
         echo 'The documentation can still be built by installing dependencies'
         echo 'in a python virtual enironment (virtualenv). This environment'
         echo "will be created in rose/${VENV_PATH} and will be removed after"
         echo 'use. To keep the virtualenv for future builds run this command'
         echo 'with the "--dev" option.'
+        echo
+        echo 'Else to override the dependency checking logic and force the docs'
+        echo 'to build use the "--force" option.'
         echo
         while read -p 'Proceed using a virtualenv (y/n)? ' usr; do
             case ${usr} in
