rose suite-run: install: handle colon in file name
Improve `rsync` commands in logic.

diff --git a/bin/rose-rug-brief-tour b/bin/rose-rug-brief-tour
--- a/bin/rose-rug-brief-tour
+++ b/bin/rose-rug-brief-tour
@@ -21,21 +21,21 @@
 #     rose-rug-brief-tour
 #
 # SYNOPSIS
-#     rose rug-brief-tour
+#     rose rug-brief-tour [DEST]
 #
 # DESCRIPTION
-#     Populate the current directory for Rose User Guide: A Brief Tour.
+#     Populate the destination directory for Rose User Guide: A Brief Tour.
+#
+# ARGUMENTS
+#     DEST - Destination directory. (default=$PWD)
 #-------------------------------------------------------------------------------
-. $(dirname $0)/../lib/bash/rose_init
-echo Copying Rose brief tour files to current directory...
-rose_init rose_log
-run rsync \
-    -a --exclude='.svn' --timeout=1800 \
-    --rsh='ssh -oBatchMode=yes -oStrictHostKeyChecking=no' \
-    $ROSE_HOME/etc/$(basename $0)/* .
-if [[ $? == 0 ]]; then
-    echo ...done
+. "$(dirname "$0")/../lib/bash/rose_init"
+echo -n 'rose rug-brief-tour: copying brief tour files to current directory...'
+rose_init 'rose_log'
+if run rsync -a "${ROSE_HOME}/etc/$(basename "$0")/" "${1:-${PWD}}"; then
+    echo 'done'
 else
-    echo ...failed
+    echo
+    echo 'rose rug-brief-tour: failed' >&2
     exit 1
 fi
