alt fix

diff --git a/metomi/rose/scripts/rose-mpi-launch b/metomi/rose/scripts/rose-mpi-launch
--- a/metomi/rose/scripts/rose-mpi-launch
+++ b/metomi/rose/scripts/rose-mpi-launch
@@ -237,14 +237,9 @@ fi
 ROSE_LAUNCHER_BASE=
 if [[ -n $ROSE_LAUNCHER ]]; then
     # Path
-    ROSE_LAUNCHER_PATH=""
-    for command in ${ROSE_LAUNCHER}; do
-        if  command="$(type -P $command)"; then
-            ROSE_LAUNCHER_PATH="${ROSE_LAUNCHER_PATH} ${command}"
-        else
-            err "ROSE_LAUNCHER: $ROSE_LAUNCHER: command not found"
-        fi
-    done
+    if ! ROSE_LAUNCHER_PATH="$(type -P $ROSE_LAUNCHER)"; then
+        err "ROSE_LAUNCHER: $ROSE_LAUNCHER: command not found"
+    fi
     ROSE_LAUNCHER=$ROSE_LAUNCHER_PATH
     ROSE_LAUNCHER_BASE="$(basename "$ROSE_LAUNCHER")"
 fi
